function MoveToInfectedAreaLast () {
    Backward()
    Foward()
    Foward()
    Foward()
    Servo_Up()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Small_backward()
    Small_Foward()
    Turn_left()
    Backward()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_left()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Small_backward()
    Small_Foward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Small_backward()
    Servo_Down()
    Backward()
    Backward()
    Servo_Up()
    Backward()
    Small_Foward()
    Small_Foward()
    Small_Foward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_left()
    Backward()
    Foward()
    Foward()
    Foward()
}
function Turn_Right () {
    PTKidsBITRobot.motorGo(30, -31.4)
    basic.pause(380)
    PTKidsBITRobot.motorStop()
}
function Turn_left () {
    PTKidsBITRobot.motorGo(-30, 31.4)
    basic.pause(380)
    PTKidsBITRobot.motorStop()
}
function Small_Foward () {
    PTKidsBITRobot.motorGo(30, 30)
    basic.pause(150)
    PTKidsBITRobot.motorStop()
}
function Foward () {
    PTKidsBITRobot.motorGo(60, 60)
    PTKidsBITRobot.motorGo(30, 31.4)
    basic.pause(1000)
    PTKidsBITRobot.motorStop()
}
function Servo_Down () {
    PTKidsBITRobot.servoWrite(Servo_Write.P8, 100)
    basic.pause(300)
    PTKidsBITRobot.servoWrite(Servo_Write.P12, 140)
    basic.pause(300)
}
input.onButtonPressed(Button.A, function () {
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_left()
    Foward()
    Foward()
    Small_backward()
    Small_Foward()
    Turn_left()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Servo_Down()
    basic.pause(100)
    MoveToInfectedArea()
    MoveToInfectedArea()
    MoveToInfectedAreaLast()
})
function MoveToInfectedArea () {
    Backward()
    Foward()
    Foward()
    Foward()
    Servo_Up()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Small_backward()
    Small_Foward()
    Turn_left()
    Backward()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_left()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Small_backward()
    Small_Foward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Small_backward()
    Servo_Down()
    Backward()
    Backward()
    Servo_Up()
    Backward()
    Small_Foward()
    Small_Foward()
    Small_Foward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Small_Foward()
    Turn_left()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Foward()
    Foward()
    Foward()
    Small_backward()
    Turn_Right()
    Backward()
    Servo_Down()
    basic.pause(100)
}
function Small_backward () {
    PTKidsBITRobot.motorGo(-30, -30)
    basic.pause(300)
    PTKidsBITRobot.motorStop()
}
function Servo_Up () {
    PTKidsBITRobot.servoWrite(Servo_Write.P12, 125)
    basic.pause(300)
    PTKidsBITRobot.servoWrite(Servo_Write.P8, 0)
    basic.pause(300)
}
function Backward () {
    PTKidsBITRobot.motorGo(-60, -60)
    PTKidsBITRobot.motorGo(-30, -31.4)
    basic.pause(1000)
    PTKidsBITRobot.motorStop()
}
